# Generated by Django 2.1.2 on 2019-05-13 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RSCompeteAPI', '0006_auto_20190513_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='work_place',
        ),
    ]
