# Generated by Django 2.1.2 on 2019-05-13 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RSCompeteAPI', '0007_auto_20190513_0227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='work_place',
            new_name='work_place_top',
        ),
    ]
