# Generated by Django 2.1.2 on 2019-05-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSCompeteAPI', '0008_auto_20190513_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='work_place',
        ),
        migrations.AlterField(
            model_name='user',
            name='work_place_top',
            field=models.CharField(default='', max_length=64),
        ),
    ]
