# Generated by Django 2.1.2 on 2019-04-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSCompeteAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='is_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='result',
            name='score',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AlterField(
            model_name='result',
            name='time_stamp',
            field=models.BigIntegerField(),
        ),
    ]
